name: parking-fairness
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.3
  - pip:
      - matplotlib==3.4.2
      - seaborn==0.11.1
      - pandas==1.3.1
      - jpype1==1.2.1
      - jupyter
      - pynetlogo==0.5.1
      - cmcrameri==1.2
      - h5py ~= 3.1.0
      - tqdm >= 4.61.0
      - wandb == 0.15.12
      - stable-baselines3[extra] == 2.1.0